### ISSUE TITLE
Mark deleted entities

### ISSUE THREAD

**Issue by jeffmcaffer** [Microsoft/ghcrawler#61]
When we detect that something is deleted (e.g., some delete event), we need to mark the entity as deleted.  likely this is reprocessing and adding a "deletedAt" property to the metadata.

* be sure to factor that into subsequent data pipelines
* decide if we need to filter deleted things at some point

**Comment by geneh** [comment]
https://developer.github.com/v3/activity/events/types/

Handle "deleted" action for IssueCommentEvent, LabelEvent, MemberEvent, MilestoneEvent(?), PullRequestReviewCommentEvent, RepositoryEvent, TeamEvent.

The following events that may have "deleted" action are not used: ProjectCardEvent, ProjectColumnEvent, ProjectEvent (no need to do anything).

**Comment by geneh** [comment]
Pull request https://github.com/Microsoft/ghcrawler/pull/74

**Comment by geneh** [comment]
The following events are not visible in event timeline:
LabelEvent, RepositoryEvent, TeamEvent, MilestoneEvent, TeamAddEvent,  DeploymentEvent, DeploymentStatusEvent, MembershipEvent, MilestoneEvent, OrganizationEvent, PageBuildEvent, StatusEvent, IssueCommentEvent if action=deleted, PullRequestReviewCommentEvent if action=deleted, MemberEvent if action=removed (and not deleted as documented).
All these events will have to be processed directly from the webhook instead of the timeline.
